- hosts: master
  become: yes
  gather_facts: true
  tasks:
    - name: get join master command
      shell: kubeadm token create --print-join-command
      register: join_command_raw

    - name: set join master command
      set_fact:
        join_cluster_command: "{{ join_command_raw.stdout_lines[0] }}"

    - debug:
        msg: "{{ join_command_raw.stdout_lines[0] }}"


- hosts: workers
  become: yes
  tasks:
    - name: remove existing settings
      command: rm -rf /etc/kubernetes

    - name: join master
      shell: "{{ hostvars['master'].join_cluster_command }} >> node_joined.txt"
      args:
        chdir: $HOME
        creates: node_joined.txt # comment this out if you want to replay join cluster

    - debug:
        msg: "{{ hostvars['master'].join_cluster_command }}"
